using System;
using System.Collections.Generic;
using System.Linq;

namespace WeldingTrainer.Domain
{
    [Flags] public enum ReflectionReason { None=0,MissingEvidence=1,TrackingInvalid=2,GenerationMismatch=4,StaleEvidence=8,InvalidVector=16,InvalidNormal=32,WrongSurfaceSide=64,OutsideModelEnvelope=128,IdealRayIntersection=256,ConeIntersection=512,NearCone=1024 }
    public sealed class ReflectionProfile
    {
        public string Id{get;} public double ConeHalfAngleRadians{get;} public double WarningMarginRadians{get;} public double SevereInnerMarginRadians{get;} public double PositionInflationMetres{get;} public double MaximumEnvelopeMetres{get;} public double MaximumAgeSeconds{get;} public double MarginalTripConfirmationSeconds{get;} public double StableLowResetSeconds{get;} public double MinimumFrontIncidenceCosine{get;}
        public ReflectionProfile(string id,double coneHalfAngle,double warningMargin,double severeInnerMargin,double inflation,double maximumEnvelope,double maximumAge,double confirmation,double stableLow,double minimumIncidenceCosine=.01)
        {if(string.IsNullOrWhiteSpace(id)||coneHalfAngle<=0||coneHalfAngle>=Math.PI/2||warningMargin<0||severeInnerMargin<0||inflation<0||maximumEnvelope<=0||maximumAge<=0||confirmation<0||confirmation>.05||stableLow<0||minimumIncidenceCosine<=0||minimumIncidenceCosine>=1)throw new ArgumentException("Invalid reflection profile");Id=id;ConeHalfAngleRadians=coneHalfAngle;WarningMarginRadians=warningMargin;SevereInnerMarginRadians=severeInnerMargin;PositionInflationMetres=inflation;MaximumEnvelopeMetres=maximumEnvelope;MaximumAgeSeconds=maximumAge;MarginalTripConfirmationSeconds=confirmation;StableLowResetSeconds=stableLow;MinimumFrontIncidenceCosine=minimumIncidenceCosine;}
    }
    public readonly struct HazardSphere {public readonly string Id;public readonly Vec3 Centre;public readonly double RadiusMetres;public readonly bool RequiredHeadTarget;public HazardSphere(string id,Vec3 centre,double radius,bool requiredHead=true){if(string.IsNullOrWhiteSpace(id)||!centre.Finite||radius<=0||!double.IsFinite(radius))throw new ArgumentException("Invalid hazard sphere");Id=id;Centre=centre;RadiusMetres=radius;RequiredHeadTarget=requiredHead;}}
    public readonly struct ReflectionInput
    {
        public readonly double EvaluationSeconds,CapturedSeconds;public readonly string SurfaceId;public readonly Vec3 ImpactPoint,IncidentDirection,SurfaceNormal;public readonly IReadOnlyList<HazardSphere> Targets;public readonly bool ImpactValid,ToolValid,HeadValid;public readonly long InputGeneration,RegistrationGeneration;
        public ReflectionInput(double evaluation,double captured,string surfaceId,Vec3 impact,Vec3 incident,Vec3 normal,IEnumerable<HazardSphere> targets,bool impactValid,bool toolValid,bool headValid,long inputGeneration,long registrationGeneration){EvaluationSeconds=evaluation;CapturedSeconds=captured;SurfaceId=surfaceId;ImpactPoint=impact;IncidentDirection=incident;SurfaceNormal=normal;Targets=(targets??Array.Empty<HazardSphere>()).ToArray();ImpactValid=impactValid;ToolValid=toolValid;HeadValid=headValid;InputGeneration=inputGeneration;RegistrationGeneration=registrationGeneration;}
    }
    public readonly struct ReflectionRiskResult
    {
        public readonly RiskState Level;public readonly ReflectionReason Reasons;public readonly string SurfaceId,ProfileId,TargetId;public readonly Vec3 ImpactPoint,IncidentDirection,SurfaceNormal,ReflectedDirection;public readonly double AngularMarginRadians,EvaluationSeconds;public readonly long InputGeneration,RegistrationGeneration;public readonly bool DirectIdealIntersection,ConeIntersection,Severe,Valid;
        public ReflectionRiskResult(RiskState level,ReflectionReason reasons,string surface,string profile,string target,Vec3 impact,Vec3 incident,Vec3 normal,Vec3 reflected,double margin,double time,long inputGeneration,long registrationGeneration,bool direct,bool cone,bool severe,bool valid){Level=level;Reasons=reasons;SurfaceId=surface;ProfileId=profile;TargetId=target;ImpactPoint=impact;IncidentDirection=incident;SurfaceNormal=normal;ReflectedDirection=reflected;AngularMarginRadians=margin;EvaluationSeconds=time;InputGeneration=inputGeneration;RegistrationGeneration=registrationGeneration;DirectIdealIntersection=direct;ConeIntersection=cone;Severe=severe;Valid=valid;}
    }
    public static class SimulatedBackReflectionEvaluator
    {
        public static ReflectionRiskResult EvaluateWorstCase(IEnumerable<ReflectionInput> footprint,ReflectionProfile profile)
        {if(footprint==null)return new ReflectionRiskResult(RiskState.Unknown,ReflectionReason.MissingEvidence,null,profile?.Id,null,default,default,default,default,double.NaN,0,0,0,false,false,false,false);ReflectionRiskResult worst=default;bool any=false;foreach(ReflectionInput input in footprint){ReflectionRiskResult result=Evaluate(input,profile);if(!any||result.Level==RiskState.Unknown||Rank(result.Level)>Rank(worst.Level)||Rank(result.Level)==Rank(worst.Level)&&result.AngularMarginRadians>worst.AngularMarginRadians)worst=result;any=true;if(result.Level==RiskState.Unknown)return result;}return any?worst:new ReflectionRiskResult(RiskState.Unknown,ReflectionReason.MissingEvidence,null,profile.Id,null,default,default,default,default,double.NaN,0,0,0,false,false,false,false);}
        public static ReflectionRiskResult Evaluate(ReflectionInput i,ReflectionProfile p)
        {
            ReflectionReason invalid=Validate(i,p);if(invalid!=ReflectionReason.None)return Unknown(i,p,invalid);
            Vec3 d=i.IncidentDirection.Normalized,n=i.SurfaceNormal.Normalized;double incidence=Vec3.Dot(d,n);if(incidence>=-p.MinimumFrontIncidenceCosine)return Unknown(i,p,ReflectionReason.WrongSurfaceSide);
            Vec3 r=(d-n*(2*incidence)).Normalized;if(!r.Finite||r.Length<.999)return Unknown(i,p,ReflectionReason.InvalidVector);
            RiskState level=RiskState.Low;ReflectionReason reasons=ReflectionReason.None;string targetId=null;double best=double.NegativeInfinity;bool direct=false,cone=false,severe=false;
            foreach(HazardSphere target in i.Targets){Vec3 v=target.Centre-i.ImpactPoint;double distance=v.Length,radius=target.RadiusMetres+p.PositionInflationMetres;if(target.RequiredHeadTarget&&distance>p.MaximumEnvelopeMetres)return Unknown(i,p,ReflectionReason.OutsideModelEnvelope);if(distance<=radius){return Result(i,p,r,target.Id,double.PositiveInfinity,RiskState.High,ReflectionReason.IdealRayIntersection|ReflectionReason.ConeIntersection,true,true,true);}
                double forward=Vec3.Dot(r,v);bool ray=forward>=0&&(v-r*forward).Length<=radius;double margin=double.NegativeInfinity;bool coneHit=false;if(forward>0){double beta=Math.Acos(Clamp(Vec3.Dot(r,v)/distance,-1,1));double angularRadius=Math.Asin(Clamp(radius/distance,0,1));margin=p.ConeHalfAngleRadians+angularRadius-beta;coneHit=margin>=0;}
                RiskState candidate=ray||coneHit?RiskState.High:margin>=-p.WarningMarginRadians?RiskState.Warning:RiskState.Low;bool candidateSevere=ray||margin>=p.SevereInnerMarginRadians;if(Rank(candidate)>Rank(level)||Rank(candidate)==Rank(level)&&margin>best){level=candidate;best=margin;targetId=target.Id;direct=ray;cone=coneHit;severe=candidateSevere;reasons=ray?ReflectionReason.IdealRayIntersection:coneHit?ReflectionReason.ConeIntersection:candidate==RiskState.Warning?ReflectionReason.NearCone:ReflectionReason.None;}}
            return Result(i,p,r,targetId,best,level,reasons,direct,cone,severe);
        }
        static ReflectionReason Validate(ReflectionInput i,ReflectionProfile p){ReflectionReason r=ReflectionReason.None;if(!i.ImpactValid||string.IsNullOrWhiteSpace(i.SurfaceId)||i.Targets==null||i.Targets.Count==0)r|=ReflectionReason.MissingEvidence;if(!i.ToolValid||!i.HeadValid)r|=ReflectionReason.TrackingInvalid;if(i.InputGeneration!=i.RegistrationGeneration)r|=ReflectionReason.GenerationMismatch;if(!double.IsFinite(i.EvaluationSeconds)||!double.IsFinite(i.CapturedSeconds)||i.EvaluationSeconds<i.CapturedSeconds||i.EvaluationSeconds-i.CapturedSeconds>p.MaximumAgeSeconds)r|=ReflectionReason.StaleEvidence;if(!i.ImpactPoint.Finite||!i.IncidentDirection.Finite||i.IncidentDirection.Length<.999)r|=ReflectionReason.InvalidVector;if(!i.SurfaceNormal.Finite||i.SurfaceNormal.Length<.999)r|=ReflectionReason.InvalidNormal;return r;}
        static ReflectionRiskResult Unknown(ReflectionInput i,ReflectionProfile p,ReflectionReason r)=>new(RiskState.Unknown,r,i.SurfaceId,p.Id,null,i.ImpactPoint,i.IncidentDirection,i.SurfaceNormal,default,double.NaN,i.EvaluationSeconds,i.InputGeneration,i.RegistrationGeneration,false,false,false,false);
        static ReflectionRiskResult Result(ReflectionInput i,ReflectionProfile p,Vec3 reflected,string target,double margin,RiskState level,ReflectionReason reason,bool direct,bool cone,bool severe)=>new(level,reason,i.SurfaceId,p.Id,target,i.ImpactPoint,i.IncidentDirection.Normalized,i.SurfaceNormal.Normalized,reflected,margin,i.EvaluationSeconds,i.InputGeneration,i.RegistrationGeneration,direct,cone,severe,true);
        static int Rank(RiskState s)=>s==RiskState.High?3:s==RiskState.Warning?2:s==RiskState.Low?1:0;static double Clamp(double x,double a,double b)=>Math.Max(a,Math.Min(b,x));
    }
    public readonly struct ReflectionFaultState {public readonly RiskState Risk;public readonly bool OutputInhibited,Latched,ConfirmationPending,ReleaseObserved,StableLow;public readonly double ConfirmationDeadline;public readonly string FaultId;public ReflectionFaultState(RiskState risk,bool inhibited,bool latched,bool pending,bool released,bool stable,double deadline,string faultId){Risk=risk;OutputInhibited=inhibited;Latched=latched;ConfirmationPending=pending;ReleaseObserved=released;StableLow=stable;ConfirmationDeadline=deadline;FaultId=faultId;}}
    public sealed class ReflectionFaultReducer
    {
        readonly ReflectionProfile profile;double highSince=double.NaN,lowSince=double.NaN,lastTime=double.NegativeInfinity;bool latched,acknowledged,releaseObserved;string faultId;long faultSequence;
        public ReflectionFaultReducer(ReflectionProfile profile){this.profile=profile??throw new ArgumentNullException(nameof(profile));}
        public ReflectionFaultState Update(ReflectionRiskResult result,bool triggerPressed)
        {double now=result.EvaluationSeconds;if(!double.IsFinite(now)||now<lastTime)throw new ArgumentException("Fault time must be monotonic");lastTime=now;if(!triggerPressed)releaseObserved=true;if(result.Level==RiskState.High){lowSince=double.NaN;if(result.Severe){Latch();}else{if(double.IsNaN(highSince))highSince=now;if(now-highSince>=profile.MarginalTripConfirmationSeconds)Latch();}}else{highSince=double.NaN;if(result.Level==RiskState.Low){if(double.IsNaN(lowSince))lowSince=now;}else lowSince=double.NaN;}bool stable=result.Level==RiskState.Low&&!double.IsNaN(lowSince)&&now-lowSince>=profile.StableLowResetSeconds;bool pending=result.Level==RiskState.High&&!latched;return new ReflectionFaultState(result.Level,result.Level!=RiskState.Low||latched,latched,pending,releaseObserved,stable,double.IsNaN(highSince)?double.NaN:highSince+profile.MarginalTripConfirmationSeconds,faultId);}
        public bool AcknowledgeAndReset(ReflectionFaultState state){acknowledged=true;if(!latched)return true;if(state.StableLow&&releaseObserved&&acknowledged){latched=false;acknowledged=false;releaseObserved=false;faultId=null;return true;}return false;}
        void Latch(){if(latched)return;latched=true;faultId="reflection-"+(++faultSequence).ToString();}
    }
}
