using System;
using System.Linq;

namespace WeldingTrainer.Domain
{
    public enum CleaningTargetPolicy { AuthoredPreWeld,AuthoredPostWeld,DerivedFromWeld }
    public sealed class CleaningTargetSnapshot
    {public string Id{get;}public string SurfaceId{get;}public CleaningTargetPolicy Policy{get;}public string SourceAttemptId{get;}public double CellMetres{get;}public int Columns{get;}public int Rows{get;}public double[] RequiredWeights{get;}public double TargetAreaSquareMetres=>RequiredWeights.Sum()*CellMetres*CellMetres;public CleaningTargetSnapshot(string id,string surface,CleaningTargetPolicy policy,string sourceAttempt,double cell,int columns,int rows,double[] weights){if(string.IsNullOrWhiteSpace(id)||string.IsNullOrWhiteSpace(surface)||cell<=0||columns<1||rows<1||weights==null||weights.Length!=columns*rows||weights.Any(x=>x<0||x>1)||weights.Sum()<=0||policy==CleaningTargetPolicy.DerivedFromWeld&&string.IsNullOrWhiteSpace(sourceAttempt))throw new ArgumentException("Invalid or empty cleaning target");Id=id;SurfaceId=surface;Policy=policy;SourceAttemptId=sourceAttempt;CellMetres=cell;Columns=columns;Rows=rows;RequiredWeights=(double[])weights.Clone();}public static bool TryCreateDerived(string id,string surface,string sourceAttempt,double cell,int columns,int rows,double[] weldWeights,out CleaningTargetSnapshot target){target=null;if(weldWeights==null||weldWeights.Sum()<=0||string.IsNullOrWhiteSpace(sourceAttempt))return false;target=new CleaningTargetSnapshot(id,surface,CleaningTargetPolicy.DerivedFromWeld,sourceAttempt,cell,columns,rows,weldWeights);return true;}}
    public sealed class CleaningProfile
    {public string Id{get;}public int Version{get;}public string Hash{get;}public ProcessMode Mode{get;}public double FootprintRadiusMetres{get;}public double MinimumSpeedMps{get;}public double MaximumSpeedMps{get;}public double MaximumStandoffMetres{get;}public double MaximumAngleRadians{get;}public double MaximumGapSeconds{get;}public CleaningProfile(string id,int version,string hash,ProcessMode mode,double radius,double minSpeed,double maxSpeed,double maxStandoff,double maxAngle,double maxGap){if(string.IsNullOrWhiteSpace(id)||version<1||string.IsNullOrWhiteSpace(hash)||(mode!=ProcessMode.PreWeldCleaning&&mode!=ProcessMode.PostWeldCleaning)||radius<=0||minSpeed<0||maxSpeed<=minSpeed||maxStandoff<=0||maxAngle<=0||maxGap<=0)throw new ArgumentException("Invalid cleaning profile");Id=id;Version=version;Hash=hash;Mode=mode;FootprintRadiusMetres=radius;MinimumSpeedMps=minSpeed;MaximumSpeedMps=maxSpeed;MaximumStandoffMetres=maxStandoff;MaximumAngleRadians=maxAngle;MaximumGapSeconds=maxGap;}}
    public readonly struct CleaningInput
    {public readonly double TimeSeconds,Umetres,Vmetres,SpeedMps,SignedStandoffMetres,AngleRadians;public readonly string SurfaceId;public readonly bool TrackingValid;public readonly ActivationDecision Activation;public readonly long RegistrationGeneration,RequiredRegistrationGeneration;public CleaningInput(double time,double u,double v,double speed,double standoff,double angle,string surface,bool tracking,ActivationDecision activation,long generation,long required){TimeSeconds=time;Umetres=u;Vmetres=v;SpeedMps=speed;SignedStandoffMetres=standoff;AngleRadians=angle;SurfaceId=surface;TrackingValid=tracking;Activation=activation;RegistrationGeneration=generation;RequiredRegistrationGeneration=required;}}
    public sealed class CleaningResult
    {public bool OutputOn{get;}public bool QualityAcceptable{get;}public double TargetAreaSquareMetres{get;}public double AttemptedAreaSquareMetres{get;}public double AcceptableAreaSquareMetres{get;}public double MissedAreaSquareMetres=>Math.Max(0,TargetAreaSquareMetres-AcceptableAreaSquareMetres);public double OverTargetAreaSquareMetres{get;}public int VisitCount{get;}public int RepeatVisitCount{get;}public double DwellSeconds{get;}public double InvalidSeconds{get;}public CleaningTargetPolicy TargetPolicy{get;}public string SourceAttemptId{get;}public CleaningResult(bool output,bool quality,double target,double attempted,double acceptable,double over,int visits,int repeats,double dwell,double invalid,CleaningTargetPolicy policy,string source){OutputOn=output;QualityAcceptable=quality;TargetAreaSquareMetres=target;AttemptedAreaSquareMetres=attempted;AcceptableAreaSquareMetres=acceptable;OverTargetAreaSquareMetres=over;VisitCount=visits;RepeatVisitCount=repeats;DwellSeconds=dwell;InvalidSeconds=invalid;TargetPolicy=policy;SourceAttemptId=source;}}
    public sealed class CleaningProcessKernel
    {readonly CleaningTargetSnapshot target;readonly CleaningProfile profile;readonly byte[] state;readonly int[] visits;bool hasPrevious,previousOn;double priorTime,priorU,priorV,dwell,invalid;int visitCount,repeats;public CleaningProcessKernel(CleaningTargetSnapshot target,CleaningProfile profile){this.target=target??throw new ArgumentNullException(nameof(target));this.profile=profile??throw new ArgumentNullException(nameof(profile));state=new byte[target.RequiredWeights.Length];visits=new int[state.Length];}
        public CleaningResult Update(CleaningInput i){if(!double.IsFinite(i.TimeSeconds)||hasPrevious&&i.TimeSeconds<=priorTime)throw new ArgumentException("Cleaning time must increase");bool evidence=i.TrackingValid&&i.RegistrationGeneration==i.RequiredRegistrationGeneration&&i.SurfaceId==target.SurfaceId&&double.IsFinite(i.Umetres)&&double.IsFinite(i.Vmetres);bool on=evidence&&i.Activation.Active;bool quality=on&&Math.Abs(i.SignedStandoffMetres)<=profile.MaximumStandoffMetres&&Math.Abs(i.AngleRadians)<=profile.MaximumAngleRadians&&i.SpeedMps>=profile.MinimumSpeedMps&&i.SpeedMps<=profile.MaximumSpeedMps;if(hasPrevious){double dt=i.TimeSeconds-priorTime;if(!evidence)invalid+=dt;if(on&&previousOn&&dt<=profile.MaximumGapSeconds){double distance=Math.Sqrt((i.Umetres-priorU)*(i.Umetres-priorU)+(i.Vmetres-priorV)*(i.Vmetres-priorV));if(distance<target.CellMetres*.1)dwell+=dt;RasterCapsule(priorU,priorV,i.Umetres,i.Vmetres,profile.FootprintRadiusMetres,quality);}}
            hasPrevious=true;previousOn=on;priorTime=i.TimeSeconds;priorU=i.Umetres;priorV=i.Vmetres;return Snapshot(on,quality);}
        public CleaningResult Stop(){previousOn=false;return Snapshot(false,false);}void RasterCapsule(double u0,double v0,double u1,double v1,double radius,bool acceptable){double minU=Math.Min(u0,u1)-radius,maxU=Math.Max(u0,u1)+radius,minV=Math.Min(v0,v1)-radius,maxV=Math.Max(v0,v1)+radius;int c0=Math.Max(0,(int)Math.Floor(minU/target.CellMetres)),c1=Math.Min(target.Columns-1,(int)Math.Floor(maxU/target.CellMetres)),r0=Math.Max(0,(int)Math.Floor(minV/target.CellMetres)),r1=Math.Min(target.Rows-1,(int)Math.Floor(maxV/target.CellMetres));for(int r=r0;r<=r1;r++)for(int c=c0;c<=c1;c++){double u=(c+.5)*target.CellMetres,v=(r+.5)*target.CellMetres;if(DistanceToSegment(u,v,u0,v0,u1,v1)>radius)continue;int index=r*target.Columns+c;if(visits[index]++>0)repeats++;visitCount++;if(target.RequiredWeights[index]>0){if(state[index]==0)state[index]=1;if(acceptable)state[index]=2;}else state[index]=3;}}
        CleaningResult Snapshot(bool output,bool quality){double cell=target.CellMetres*target.CellMetres,attempted=0,acceptable=0,over=0;for(int i=0;i<state.Length;i++){if(target.RequiredWeights[i]>0&&state[i]>0)attempted+=target.RequiredWeights[i]*cell;if(target.RequiredWeights[i]>0&&state[i]==2)acceptable+=target.RequiredWeights[i]*cell;if(target.RequiredWeights[i]==0&&state[i]==3)over+=cell;}return new CleaningResult(output,quality,target.TargetAreaSquareMetres,attempted,acceptable,over,visitCount,repeats,dwell,invalid,target.Policy,target.SourceAttemptId);}
        static double DistanceToSegment(double u,double v,double u0,double v0,double u1,double v1){double du=u1-u0,dv=v1-v0,l2=du*du+dv*dv;if(l2<1e-18)return Math.Sqrt((u-u0)*(u-u0)+(v-v0)*(v-v0));double t=Math.Max(0,Math.Min(1,((u-u0)*du+(v-v0)*dv)/l2)),x=u0+t*du,y=v0+t*dv;return Math.Sqrt((u-x)*(u-x)+(v-y)*(v-y));}}
    public enum NozzleChangeStatus { Stable,ChangePending }
    public readonly struct NozzleChangeSnapshot {public readonly NozzleState Installed,Requested,Effective;public readonly NozzleChangeStatus Status;public readonly long TransactionId;public readonly string Event;public NozzleChangeSnapshot(NozzleState installed,NozzleState requested,NozzleChangeStatus status,long id,string e){Installed=installed;Requested=requested;Status=status;TransactionId=id;Event=e;Effective=status==NozzleChangeStatus.Stable?installed:NozzleState.Unknown;}}
    public sealed class NozzleChangeWorkflow
    {NozzleState installed;NozzleState requested;NozzleChangeStatus status;long transaction;public NozzleChangeWorkflow(NozzleState initial=NozzleState.Unknown){installed=initial;}public NozzleChangeSnapshot Begin(NozzleState next,bool disarmed,bool triggerReleased,bool fault){if(status==NozzleChangeStatus.ChangePending||next==NozzleState.Unknown||!disarmed||!triggerReleased||fault)throw new InvalidOperationException("Nozzle change not permitted");requested=next;status=NozzleChangeStatus.ChangePending;return State("begin");}public NozzleChangeSnapshot Confirm(long id,bool disarmed,bool fault){if(status!=NozzleChangeStatus.ChangePending||id!=transaction||!disarmed||fault)throw new InvalidOperationException("Stale or unsafe nozzle confirmation");installed=requested;requested=NozzleState.Unknown;status=NozzleChangeStatus.Stable;return State("confirm");}public NozzleChangeSnapshot Cancel(string reason="cancel"){requested=NozzleState.Unknown;status=NozzleChangeStatus.Stable;return State(reason);}public NozzleChangeSnapshot OnFault()=>status==NozzleChangeStatus.ChangePending?Cancel("fault-cancel"):State("fault");public NozzleChangeSnapshot Current=>State(null);NozzleChangeSnapshot State(string e){if(e=="begin")transaction++;return new NozzleChangeSnapshot(installed,requested,status,transaction,e);}}
}
