using System;
using System.Linq;

namespace WeldingTrainer.Domain
{
    [Flags] public enum FusionQualityFlags { None=0,Position=1,Speed=2,TravelAngle=4,WorkAngle=8,Reverse=16 }
    [Flags] public enum FusionBlockReason { None=0,Interlock=1,StartGate=2,InvalidEvaluation=4,Discontinuity=8,GenerationMismatch=16 }
    public sealed class FusionProfile
    {
        public string Id{get;}public int Version{get;}public string Hash{get;}public string SeamId{get;}public double MaximumLateralErrorMetres{get;}public double MaximumNormalErrorMetres{get;}public double MinimumSpeedMps{get;}public double MaximumSpeedMps{get;}public double MaximumTravelAngleRadians{get;}public double MaximumWorkAngleRadians{get;}public double StartGateMetres{get;}public double EndGateMetres{get;}public double MaximumIntervalSeconds{get;}public double MaximumAttributableStepMetres{get;}public double CompletionGapToleranceMetres{get;}public double TrainingFootprintWidthMetres{get;}
        public FusionProfile(string id,int version,string hash,string seamId,double maxLateral,double maxNormal,double minSpeed,double maxSpeed,double maxTravel,double maxWork,double startGate,double endGate,double maxInterval,double maxStep,double gapTolerance,double footprintWidth)
        {if(string.IsNullOrWhiteSpace(id)||version<1||string.IsNullOrWhiteSpace(hash)||string.IsNullOrWhiteSpace(seamId)||maxLateral<=0||maxNormal<=0||minSpeed<0||maxSpeed<=minSpeed||maxTravel<=0||maxWork<=0||startGate<0||endGate<0||maxInterval<=0||maxStep<=0||gapTolerance<0||footprintWidth<=0)throw new ArgumentException("Invalid Fusion profile");Id=id;Version=version;Hash=hash;SeamId=seamId;MaximumLateralErrorMetres=maxLateral;MaximumNormalErrorMetres=maxNormal;MinimumSpeedMps=minSpeed;MaximumSpeedMps=maxSpeed;MaximumTravelAngleRadians=maxTravel;MaximumWorkAngleRadians=maxWork;StartGateMetres=startGate;EndGateMetres=endGate;MaximumIntervalSeconds=maxInterval;MaximumAttributableStepMetres=maxStep;CompletionGapToleranceMetres=gapTolerance;TrainingFootprintWidthMetres=footprintWidth;}
    }
    public readonly struct FusionInput
    {public readonly double TimeSeconds;public readonly PathMetrics Path;public readonly ActivationDecision Activation;public readonly long RegistrationGeneration,RequiredRegistrationGeneration;public FusionInput(double time,PathMetrics path,ActivationDecision activation,long generation,long required){TimeSeconds=time;Path=path;Activation=activation;RegistrationGeneration=generation;RequiredRegistrationGeneration=required;}}
    public readonly struct CoverageDelta
    {public readonly bool Valid;public readonly string AttemptId,ProfileId,SeamId;public readonly ProcessMode Mode;public readonly long RegistrationGeneration,ActivationEpoch;public readonly double StartArcMetres,EndArcMetres,StartSeconds,EndSeconds;public readonly CoverageQuality Quality;public CoverageDelta(bool valid,string attempt,string profile,string seam,long generation,long epoch,double start,double end,double startTime,double endTime,CoverageQuality quality){Valid=valid;AttemptId=attempt;ProfileId=profile;SeamId=seam;Mode=ProcessMode.Fusion;RegistrationGeneration=generation;ActivationEpoch=epoch;StartArcMetres=start;EndArcMetres=end;StartSeconds=startTime;EndSeconds=endTime;Quality=quality;}}
    public readonly struct FusionMetrics
    {public readonly double ActiveSeconds,BlockedTriggerSeconds,InvalidSeconds,MeanAbsoluteLateralErrorMetres,MeanAbsoluteNormalErrorMetres,MeanAbsoluteSpeedErrorMps,MeanAbsoluteTravelAngleErrorRadians,MeanAbsoluteWorkAngleErrorRadians;public readonly int ReverseIntervals,ActivationEpochs;public FusionMetrics(double active,double blocked,double invalid,double lateral,double normal,double speed,double travel,double work,int reverse,int epochs){ActiveSeconds=active;BlockedTriggerSeconds=blocked;InvalidSeconds=invalid;MeanAbsoluteLateralErrorMetres=lateral;MeanAbsoluteNormalErrorMetres=normal;MeanAbsoluteSpeedErrorMps=speed;MeanAbsoluteTravelAngleErrorRadians=travel;MeanAbsoluteWorkAngleErrorRadians=work;ReverseIntervals=reverse;ActivationEpochs=epochs;}}
    public sealed class FusionResult
    {public bool OutputOn{get;}public bool Acceptable{get;}public bool Complete{get;}public FusionQualityFlags QualityFlags{get;}public FusionBlockReason BlockReasons{get;}public CoverageDelta Delta{get;}public CoverageSnapshot Coverage{get;}public FusionMetrics Metrics{get;}public FusionResult(bool output,bool acceptable,bool complete,FusionQualityFlags quality,FusionBlockReason blocked,CoverageDelta delta,CoverageSnapshot coverage,FusionMetrics metrics){OutputOn=output;Acceptable=acceptable;Complete=complete;QualityFlags=quality;BlockReasons=blocked;Delta=delta;Coverage=coverage;Metrics=metrics;}}
    public sealed class FusionProcessKernel
    {
        readonly string attemptId;readonly DirectedSpline seam;readonly FusionProfile profile;readonly SeamCoverageTracker coverage;bool hasPrevious,previousOn,startAccepted;double previousTime,previousArc,active,blocked,invalid,lateralWeighted,normalWeighted,speedWeighted,travelWeighted,workWeighted,qualityTime;long epoch;int reverse;
        public FusionProcessKernel(string attemptId,DirectedSpline seam,FusionProfile profile){this.attemptId=string.IsNullOrWhiteSpace(attemptId)?throw new ArgumentException("Attempt ID required"):attemptId;this.seam=seam??throw new ArgumentNullException(nameof(seam));this.profile=profile??throw new ArgumentNullException(nameof(profile));if(seam.Id!=profile.SeamId)throw new ArgumentException("Fusion profile/seam mismatch");coverage=new SeamCoverageTracker(seam,profile.MaximumAttributableStepMetres);}
        public FusionResult Update(FusionInput input)
        {
            if(!double.IsFinite(input.TimeSeconds)||hasPrevious&&input.TimeSeconds<=previousTime)throw new ArgumentException("Fusion time must be finite and increasing");double dt=hasPrevious?input.TimeSeconds-previousTime:0;FusionBlockReason block=FusionBlockReason.None;if(input.RegistrationGeneration!=input.RequiredRegistrationGeneration)block|=FusionBlockReason.GenerationMismatch;if(input.Path==null||!input.Path.Valid||!input.Path.Projection.Valid)block|=FusionBlockReason.InvalidEvaluation;if(input.Path!=null&&(input.Path.Flags&(MotionFlags.Discontinuity|MotionFlags.SkippedRegion|MotionFlags.TrackingGap|MotionFlags.AmbiguousProjection))!=0)block|=FusionBlockReason.Discontinuity;if(!input.Activation.Active)block|=FusionBlockReason.Interlock;
            if(!startAccepted&&block==FusionBlockReason.None){if(input.Path.Projection.ArcLengthMetres<=profile.StartGateMetres)startAccepted=true;else block|=FusionBlockReason.StartGate;}
            bool output=block==FusionBlockReason.None;if(output&&!previousOn)epoch++;if(input.Activation.Requested&&!output)blocked+=dt;if((block&(FusionBlockReason.InvalidEvaluation|FusionBlockReason.GenerationMismatch|FusionBlockReason.Discontinuity))!=0)invalid+=dt;
            FusionQualityFlags quality=Quality(input.Path);bool acceptable=quality==FusionQualityFlags.None;CoverageDelta delta=default;double currentArc=input.Path?.Projection.ArcLengthMetres??0;
            if(output&&previousOn&&dt<=profile.MaximumIntervalSeconds&&Math.Abs(currentArc-previousArc)<=profile.MaximumAttributableStepMetres){double a=Math.Min(previousArc,currentArc),b=Math.Max(previousArc,currentArc);if(b-a>1e-9)delta=new CoverageDelta(true,attemptId,profile.Id,seam.Id,input.RegistrationGeneration,epoch,a,b,previousTime,input.TimeSeconds,acceptable?CoverageQuality.Acceptable:CoverageQuality.Poor);active+=dt;Accumulate(input.Path,dt,quality);}else if(output&&previousOn){block|=FusionBlockReason.Discontinuity;output=false;invalid+=dt;}
            ActivationDecision coverageActivation=output?input.Activation:new ActivationDecision(ActivationState.Inhibited,BlockReason.ProcessPrerequisiteMissing,input.Activation.Requested);CoverageSnapshot snapshot=coverage.Update(input.Path,coverageActivation,acceptable,input.RegistrationGeneration,input.RequiredRegistrationGeneration);bool complete=Completion(snapshot,input.Path);
            previousOn=output;previousTime=input.TimeSeconds;previousArc=currentArc;hasPrevious=true;return new FusionResult(output,acceptable,complete,quality,block,delta,snapshot,Metrics());
        }
        public FusionResult Stop(double time){if(hasPrevious&&time<previousTime)throw new ArgumentException("Stop time precedes sample");previousOn=false;CoverageSnapshot snapshot=coverage.Stop();return new FusionResult(false,false,false,FusionQualityFlags.None,FusionBlockReason.Interlock,default,snapshot,Metrics());}
        FusionQualityFlags Quality(PathMetrics p){if(p==null||!p.Valid)return FusionQualityFlags.None;FusionQualityFlags q=FusionQualityFlags.None;if(Math.Abs(p.LateralErrorMetres)>profile.MaximumLateralErrorMetres||Math.Abs(p.NormalErrorMetres)>profile.MaximumNormalErrorMetres)q|=FusionQualityFlags.Position;if(!p.SpeedValid||Math.Abs(p.FilteredSpeedMps)<profile.MinimumSpeedMps||Math.Abs(p.FilteredSpeedMps)>profile.MaximumSpeedMps)q|=FusionQualityFlags.Speed;if(!p.TravelAngleValid||Math.Abs(p.TravelAngleRadians)>profile.MaximumTravelAngleRadians)q|=FusionQualityFlags.TravelAngle;if(!p.WorkAngleValid||Math.Abs(p.WorkAngleRadians)>profile.MaximumWorkAngleRadians)q|=FusionQualityFlags.WorkAngle;if(p.Flags.HasFlag(MotionFlags.Reverse))q|=FusionQualityFlags.Reverse;return q;}
        void Accumulate(PathMetrics p,double dt,FusionQualityFlags q){qualityTime+=dt;lateralWeighted+=Math.Abs(p.LateralErrorMetres)*dt;normalWeighted+=Math.Abs(p.NormalErrorMetres)*dt;double target=(profile.MinimumSpeedMps+profile.MaximumSpeedMps)/2;speedWeighted+=Math.Abs(Math.Abs(p.FilteredSpeedMps)-target)*dt;travelWeighted+=Math.Abs(p.TravelAngleRadians)*dt;workWeighted+=Math.Abs(p.WorkAngleRadians)*dt;if(q.HasFlag(FusionQualityFlags.Reverse))reverse++;}
        bool Completion(CoverageSnapshot snapshot,PathMetrics p){if(p==null||!p.Projection.Valid||p.Projection.ArcLengthMetres<seam.LengthMetres-profile.EndGateMetres)return false;double cursor=0;foreach(CoverageInterval interval in snapshot.Intervals.Where(x=>x.Quality==CoverageQuality.Acceptable).OrderBy(x=>x.StartArcMetres)){if(interval.StartArcMetres-cursor>profile.CompletionGapToleranceMetres)return false;cursor=Math.Max(cursor,interval.EndArcMetres);}return cursor>=seam.LengthMetres-profile.EndGateMetres;}
        FusionMetrics Metrics(){double d=Math.Max(qualityTime,1e-12);return new FusionMetrics(active,blocked,invalid,lateralWeighted/d,normalWeighted/d,speedWeighted/d,travelWeighted/d,workWeighted/d,reverse,(int)epoch);}
    }
}
