using System;
using System.Collections.Generic;

namespace WeldingTrainer.Domain
{
    public sealed class PulseProfile
    {
        public string Id{get;}public int Version{get;}public string Hash{get;}public string SeamId{get;}public double PeriodSeconds{get;}public double DutyFraction{get;}public double OnSeconds=>PeriodSeconds*DutyFraction;public double SpotDiameterMetres{get;}public double MaximumSampleGapSeconds{get;}public int MaximumWindowsPerInterval{get;}public double ClockToleranceSeconds{get;}
        public PulseProfile(string id,int version,string hash,string seamId,double period,double duty,double spotDiameter,double maximumGap,int maximumWindows=4096,double clockTolerance=1e-10)
        {if(string.IsNullOrWhiteSpace(id)||version<1||string.IsNullOrWhiteSpace(hash)||string.IsNullOrWhiteSpace(seamId)||!double.IsFinite(period)||period<=0||!double.IsFinite(duty)||duty<=0||duty>1||spotDiameter<=0||maximumGap<=0||maximumWindows<1||clockTolerance<0||Math.Ceiling(maximumGap/period)+2>maximumWindows)throw new ArgumentException("Invalid or unsupported Pulse profile");Id=id;Version=version;Hash=hash;SeamId=seamId;PeriodSeconds=period;DutyFraction=duty;SpotDiameterMetres=spotDiameter;MaximumSampleGapSeconds=maximumGap;MaximumWindowsPerInterval=maximumWindows;ClockToleranceSeconds=clockTolerance;}
    }
    public readonly struct PulseInput {public readonly double TimeSeconds;public readonly PathMetrics Path;public readonly ActivationDecision Activation;public readonly bool QualityAcceptable;public readonly long RegistrationGeneration,RequiredRegistrationGeneration;public PulseInput(double time,PathMetrics path,ActivationDecision activation,bool quality,long generation,long required){TimeSeconds=time;Path=path;Activation=activation;QualityAcceptable=quality;RegistrationGeneration=generation;RequiredRegistrationGeneration=required;}}
    public readonly struct PulseWindowEvidence
    {public readonly long Epoch,PulseIndex,RegistrationGeneration;public readonly string ProfileId,ProfileHash,SeamId;public readonly double WindowStartSeconds,WindowEndSeconds,ArcStartMetres,ArcEndMetres;public readonly CoverageQuality Quality;public PulseWindowEvidence(long epoch,long index,long generation,string profile,string hash,string seam,double start,double end,double arcStart,double arcEnd,CoverageQuality quality){Epoch=epoch;PulseIndex=index;RegistrationGeneration=generation;ProfileId=profile;ProfileHash=hash;SeamId=seam;WindowStartSeconds=start;WindowEndSeconds=end;ArcStartMetres=arcStart;ArcEndMetres=arcEnd;Quality=quality;}}
    public sealed class PulseResult
    {public bool Requested{get;}public bool OutputOnAtSample{get;}public long Epoch{get;}public long PulseIndex{get;}public double EpochStartSeconds{get;}public double PeriodSeconds{get;}public double DutyFraction{get;}public double ActiveDurationSeconds{get;}public IReadOnlyList<PulseWindowEvidence> Windows{get;}public CoverageSnapshot Coverage{get;}public PulseResult(bool requested,bool on,long epoch,long index,double epochStart,double period,double duty,double active,IReadOnlyList<PulseWindowEvidence> windows,CoverageSnapshot coverage){Requested=requested;OutputOnAtSample=on;Epoch=epoch;PulseIndex=index;EpochStartSeconds=epochStart;PeriodSeconds=period;DutyFraction=duty;ActiveDurationSeconds=active;Windows=windows;Coverage=coverage;}}
    public sealed class PulsedProcessKernel
    {
        readonly DirectedSpline seam;readonly PulseProfile profile;readonly SeamCoverageTracker coverage;bool epochActive,hasPrevious,previousActive;double epochStart,previousTime,previousArc,activeDuration;long epoch;
        public PulsedProcessKernel(DirectedSpline seam,PulseProfile profile){this.seam=seam??throw new ArgumentNullException(nameof(seam));this.profile=profile??throw new ArgumentNullException(nameof(profile));if(seam.Id!=profile.SeamId)throw new ArgumentException("Pulse profile/seam mismatch");coverage=new SeamCoverageTracker(seam,seam.LengthMetres);}
        public PulseResult Update(PulseInput input)
        {if(!double.IsFinite(input.TimeSeconds)||hasPrevious&&input.TimeSeconds<=previousTime)throw new ArgumentException("Pulse time must be finite and increasing");bool valid=input.Path!=null&&input.Path.Valid&&input.Path.Projection.Valid&&input.RegistrationGeneration==input.RequiredRegistrationGeneration;bool active=input.Activation.Active&&valid;var windows=new List<PulseWindowEvidence>();if(active&&!epochActive){epochActive=true;epoch++;epochStart=input.TimeSeconds;}
            if(previousActive&&valid){double dt=input.TimeSeconds-previousTime;if(dt<=profile.MaximumSampleGapSeconds){Intersect(previousTime,input.TimeSeconds,previousArc,input.Path.Projection.ArcLengthMetres,input.QualityAcceptable,input.RegistrationGeneration,windows);}else{epochActive=false;active=false;coverage.Stop();}}
            if(!active){epochActive=false;coverage.Stop();}previousActive=active;previousTime=input.TimeSeconds;previousArc=input.Path?.Projection.ArcLengthMetres??0;hasPrevious=true;long index=epochActive?Index(input.TimeSeconds):0;bool on=epochActive&&IsOn(input.TimeSeconds);return new PulseResult(input.Activation.Requested,on,epoch,index,epochStart,profile.PeriodSeconds,profile.DutyFraction,activeDuration,windows.AsReadOnly(),Snapshot());}
        public PulseResult Stop(double time){epochActive=false;previousActive=false;return new PulseResult(false,false,epoch,0,epochStart,profile.PeriodSeconds,profile.DutyFraction,activeDuration,Array.Empty<PulseWindowEvidence>(),coverage.Stop());}
        void Intersect(double start,double end,double startArc,double endArc,bool acceptable,long generation,List<PulseWindowEvidence> evidence)
        {long first=(long)Math.Floor((start-epochStart)/profile.PeriodSeconds);long last=(long)Math.Floor((end-epochStart)/profile.PeriodSeconds);if(last-first+1>profile.MaximumWindowsPerInterval)throw new InvalidOperationException("Pulse interval exceeds deterministic work bound");for(long k=Math.Max(0,first);k<=last;k++){double onStart=epochStart+k*profile.PeriodSeconds,onEnd=onStart+profile.OnSeconds;double a=Math.Max(start,onStart),b=Math.Min(end,onEnd);if(b-a<=profile.ClockToleranceSeconds)continue;double ta=(a-start)/(end-start),tb=(b-start)/(end-start),arcA=startArc+(endArc-startArc)*ta,arcB=startArc+(endArc-startArc)*tb,r=profile.SpotDiameterMetres/2;coverage.AddAttributedInterval(Math.Min(arcA,arcB)-r,Math.Max(arcA,arcB)+r,acceptable?CoverageQuality.Acceptable:CoverageQuality.Poor);activeDuration+=b-a;evidence.Add(new PulseWindowEvidence(epoch,k,generation,profile.Id,profile.Hash,seam.Id,a,b,arcA,arcB,acceptable?CoverageQuality.Acceptable:CoverageQuality.Poor));}}
        long Index(double time)=>Math.Max(0,(long)Math.Floor((time-epochStart)/profile.PeriodSeconds));bool IsOn(double time){double phase=(time-epochStart)-Index(time)*profile.PeriodSeconds;return phase>=0&&phase<profile.OnSeconds;}
        CoverageSnapshot Snapshot()=>coverage.Current;
    }
}
