using System;
using System.Collections.Generic;

namespace WeldingTrainer.Domain
{
    public enum ProcessMode { Fusion, Wobble, Pulsed, PreWeldCleaning, PostWeldCleaning }
    public enum SessionState { Idle, Initializing, Registering, Selecting, Ready, Running, Suspended, Saving, Reviewing, Completed, Aborted, Faulted }
    public enum ActivationState { Inhibited, ResetRequired, ReadyDisarmed, Armed, Active }
    public enum NozzleState { Unknown, Welding, Cleaning }
    public enum ClampState { Disconnected, Connected }
    [Flags] public enum BlockReason : ulong { None=0, NoSession=1, RegistrationInvalid=2, OriginMismatch=4, HeadInvalid=8, ToolInvalid=16, StaleInput=32, NozzleUnknown=64, NozzleMismatch=128, ClampDisconnected=256, SafetyUnknown=512, SafetyRejected=1024, RecorderUnavailable=2048, TriggerReleaseRequired=4096, EmergencyStop=8192, FaultLatched=16384, AssemblyUnconfirmed=32768, BindingMismatch=65536, ContactInvalid=131072, OutsideFiniteSurface=262144, WrongApproach=524288, AmbiguousSurface=1048576, ReflectionUnknown=2097152, ReflectionUnsafe=4194304, ProcessPrerequisiteMissing=8388608, MenuOpen=16777216, SystemInvalid=33554432 }

    public readonly struct Vec3 { public readonly double X,Y,Z; public Vec3(double x,double y,double z){X=x;Y=y;Z=z;} public bool Finite=>double.IsFinite(X)&&double.IsFinite(Y)&&double.IsFinite(Z); public double Length=>Math.Sqrt(X*X+Y*Y+Z*Z); public double LengthSquared=>X*X+Y*Y+Z*Z; public Vec3 Normalized=>Length>1e-12?this/Length:default; public static Vec3 operator+(Vec3 a,Vec3 b)=>new(a.X+b.X,a.Y+b.Y,a.Z+b.Z);public static Vec3 operator-(Vec3 a,Vec3 b)=>new(a.X-b.X,a.Y-b.Y,a.Z-b.Z);public static Vec3 operator*(Vec3 a,double s)=>new(a.X*s,a.Y*s,a.Z*s);public static Vec3 operator/(Vec3 a,double s)=>new(a.X/s,a.Y/s,a.Z/s);public static double Dot(Vec3 a,Vec3 b)=>a.X*b.X+a.Y*b.Y+a.Z*b.Z;public static Vec3 Cross(Vec3 a,Vec3 b)=>new(a.Y*b.Z-a.Z*b.Y,a.Z*b.X-a.X*b.Z,a.X*b.Y-a.Y*b.X); }
    public readonly struct Quat { public readonly double X,Y,Z,W; public Quat(double x,double y,double z,double w){X=x;Y=y;Z=z;W=w;} public bool Finite=>double.IsFinite(X)&&double.IsFinite(Y)&&double.IsFinite(Z)&&double.IsFinite(W); }
    public readonly struct RigidPose { public readonly string DestinationFrame,SourceFrame; public readonly Vec3 PositionMetres; public readonly Quat Rotation; public RigidPose(string destination,string source,Vec3 p,Quat q){DestinationFrame=destination;SourceFrame=source;PositionMetres=p;Rotation=q;} }
    public sealed class ProcessProfile { public string Id{get;} public int Version{get;} public ProcessMode Mode{get;} public string Hash{get;} public double MaximumSampleGapSeconds{get;} public ProcessProfile(string id,int version,ProcessMode mode,string hash,double maxGap){if(string.IsNullOrWhiteSpace(id)||version<1||string.IsNullOrWhiteSpace(hash)||maxGap<=0)throw new ArgumentException("Invalid profile");Id=id;Version=version;Mode=mode;Hash=hash;MaximumSampleGapSeconds=maxGap;} }
    public sealed class ProcessConfiguration { public const int SchemaVersion=1; public string FixtureId{get;} public string SeamId{get;} public ProcessProfile Profile{get;} public string SourceAttemptId{get;} public ProcessConfiguration(string fixture,string seam,ProcessProfile profile,string sourceAttempt=null){FixtureId=fixture??throw new ArgumentNullException(nameof(fixture));SeamId=seam??throw new ArgumentNullException(nameof(seam));Profile=profile??throw new ArgumentNullException(nameof(profile));SourceAttemptId=sourceAttempt;} }
    public sealed class AttemptConfiguration { public string AttemptId{get;} public ProcessConfiguration Process{get;} public long RegistrationGeneration{get;} public AttemptConfiguration(string id,ProcessConfiguration process,long generation){AttemptId=id;Process=process;RegistrationGeneration=generation;} }
    public sealed class ProcessSnapshot { public long Sequence{get;} public string SessionId{get;} public string AttemptId{get;} public SessionState Session{get;} public ActivationState Activation{get;} public NozzleState Nozzle{get;} public ClampState Clamp{get;} public BlockReason Reasons{get;} public bool Requested{get;} public bool Permission=>Activation==ActivationState.Armed||Activation==ActivationState.Active; public ProcessSnapshot(long seq,string session,string attempt,SessionState state,ActivationState activation,NozzleState nozzle,ClampState clamp,BlockReason reasons,bool requested){Sequence=seq;SessionId=session;AttemptId=attempt;Session=state;Activation=activation;Nozzle=nozzle;Clamp=clamp;Reasons=reasons;Requested=requested;} }
    public enum ProcessEventType { SessionStarted,StateChanged,RegistrationAccepted,AttemptPrepared,NozzleChanged,ClampChanged,Armed,Disarmed,Suspended,Resumed,SavingStarted,ReviewReady,SaveFailed,EmergencyStop,EmergencyResetRejected,EmergencyReset,Rearmed,SessionCompleted,SessionAborted }
    public sealed class ProcessEvent { public const int SchemaVersion=1; public long Sequence{get;} public double MonotonicSeconds{get;} public string SessionId{get;} public string AttemptId{get;} public long InputGeneration{get;} public long RegistrationGeneration{get;} public string ProfileHash{get;} public ProcessEventType Type{get;} public string Payload{get;} public ProcessEvent(long sequence,double time,string session,string attempt,long inputGen,long registrationGen,string profileHash,ProcessEventType type,string payload){Sequence=sequence;MonotonicSeconds=time;SessionId=session;AttemptId=attempt;InputGeneration=inputGen;RegistrationGeneration=registrationGen;ProfileHash=profileHash;Type=type;Payload=payload??"";} }
}
