using System;
using System.Collections.Generic;
using System.Linq;

namespace WeldingTrainer.Domain
{
    public sealed class DirectedSpline
    {
        readonly Vec3[] points; readonly double[] arc;
        public string Id{get;} public IReadOnlyList<Vec3> Points=>Array.AsReadOnly(points); public double LengthMetres=>arc[arc.Length-1];
        public DirectedSpline(string id,IEnumerable<Vec3> values){Id=id;points=values?.ToArray()??Array.Empty<Vec3>();if(points.Length<2||points.Any(x=>!x.Finite))throw new ArgumentException("Spline needs finite points");arc=new double[points.Length];for(int i=1;i<points.Length;i++){double d=(points[i]-points[i-1]).Length;if(d<=1e-9)throw new ArgumentException("Degenerate segment");arc[i]=arc[i-1]+d;}}
        public SeamProjection Project(Vec3 p,double? priorArc=null,double searchRadius=.25)
        {SeamProjection best=default;double bestDistance=double.PositiveInfinity;int equallyClose=0;for(int i=0;i<points.Length-1;i++){Vec3 d=points[i+1]-points[i];double t=Math.Max(0,Math.Min(1,Vec3.Dot(p-points[i],d)/d.LengthSquared));double s=arc[i]+t*d.Length;if(priorArc.HasValue&&Math.Abs(s-priorArc.Value)>searchRadius)continue;Vec3 q=points[i]+d*t;double distance=(p-q).Length;if(distance<bestDistance-1e-8){bestDistance=distance;equallyClose=1;best=new SeamProjection(true,false,i,s,s/LengthMetres,q,d.Normalized);}else if(Math.Abs(distance-bestDistance)<=1e-8)equallyClose++;}if(double.IsPositiveInfinity(bestDistance))return default;return new SeamProjection(true,equallyClose>1,best.SegmentIndex,best.ArcLengthMetres,best.Progress,best.Position,best.Tangent);}
    }
    public readonly struct SeamProjection { public readonly bool Valid,Ambiguous;public readonly int SegmentIndex;public readonly double ArcLengthMetres,Progress;public readonly Vec3 Position,Tangent;public SeamProjection(bool valid,bool ambiguous,int segment,double arc,double progress,Vec3 position,Vec3 tangent){Valid=valid;Ambiguous=ambiguous;SegmentIndex=segment;ArcLengthMetres=arc;Progress=progress;Position=position;Tangent=tangent;} }
    public enum SpeedClass { Invalid, TooSlow, Correct, TooFast }
    [Flags] public enum MotionFlags { None=0, Reverse=1, Discontinuity=2, SkippedRegion=4, TrackingGap=8, NonMonotonicTime=16, AmbiguousProjection=32, GenerationMismatch=64 }
    public readonly struct PathSample { public readonly double Time;public readonly Vec3 Tip,ToolForward,SurfaceNormal;public readonly bool TrackingValid;public readonly long RegistrationGeneration,OriginGeneration;public PathSample(double time,Vec3 tip,Vec3 forward,Vec3 normal,bool valid,long registration,long origin){Time=time;Tip=tip;ToolForward=forward;SurfaceNormal=normal;TrackingValid=valid;RegistrationGeneration=registration;OriginGeneration=origin;} }
    public sealed class PathMetrics
    {public bool Valid{get;}public SeamProjection Projection{get;}public Vec3 ErrorVector{get;}public double TangentialErrorMetres{get;}public double LateralErrorMetres{get;}public double NormalErrorMetres{get;}public double TotalErrorMetres{get;}public bool SpeedValid{get;}public double SignedSpeedMps{get;}public double FilteredSpeedMps{get;}public SpeedClass SpeedClass{get;}public bool TravelAngleValid{get;}public double TravelAngleRadians{get;}public bool WorkAngleValid{get;}public double WorkAngleRadians{get;}public MotionFlags Flags{get;}public PathMetrics(bool valid,SeamProjection projection,Vec3 error,double tangent,double lateral,double normal,bool speedValid,double speed,double filtered,SpeedClass speedClass,bool travelValid,double travel,bool workValid,double work,MotionFlags flags){Valid=valid;Projection=projection;ErrorVector=error;TangentialErrorMetres=tangent;LateralErrorMetres=lateral;NormalErrorMetres=normal;TotalErrorMetres=error.Length;SpeedValid=speedValid;SignedSpeedMps=speed;FilteredSpeedMps=filtered;SpeedClass=speedClass;TravelAngleValid=travelValid;TravelAngleRadians=travel;WorkAngleValid=workValid;WorkAngleRadians=work;Flags=flags;}}
    public sealed class PathEvaluationPolicy {public readonly double MinSpeed,MaxSpeed,FilterTau,MaxGap,MaxArcJump,ReverseTolerance,MinMotion;public PathEvaluationPolicy(double min,double max,double tau,double gap,double jump,double reverse,double minMotion){if(min<0||max<=min||tau<=0||gap<=0||jump<=0||reverse<0||minMotion<=0)throw new ArgumentException("Invalid path policy");MinSpeed=min;MaxSpeed=max;FilterTau=tau;MaxGap=gap;MaxArcJump=jump;ReverseTolerance=reverse;MinMotion=minMotion;}}
    public sealed class WeldPathEvaluator
    {
        readonly DirectedSpline spline;readonly PathEvaluationPolicy policy;bool hasPrevious;PathSample previous;SeamProjection previousProjection;double filtered;
        public WeldPathEvaluator(DirectedSpline spline,PathEvaluationPolicy policy){this.spline=spline;this.policy=policy;}
        public void Reset(){hasPrevious=false;filtered=0;}
        public PathMetrics Evaluate(PathSample sample,long requiredRegistration,long requiredOrigin)
        {MotionFlags flags=MotionFlags.None;if(!sample.TrackingValid){Reset();return Invalid(MotionFlags.TrackingGap);}if(sample.RegistrationGeneration!=requiredRegistration||sample.OriginGeneration!=requiredOrigin){Reset();return Invalid(MotionFlags.GenerationMismatch);}double? prior=hasPrevious?previousProjection.ArcLengthMetres:null;SeamProjection projection=spline.Project(sample.Tip,prior,policy.MaxArcJump*2);if(!projection.Valid){Reset();return Invalid(MotionFlags.Discontinuity);}if(projection.Ambiguous)flags|=MotionFlags.AmbiguousProjection;Vec3 normal=sample.SurfaceNormal.Normalized;if(normal.Length<.999){Reset();return Invalid(flags);}Vec3 lateralAxis=Vec3.Cross(normal,projection.Tangent).Normalized;Vec3 error=sample.Tip-projection.Position;double tangential=Vec3.Dot(error,projection.Tangent),lateral=Vec3.Dot(error,lateralAxis),normalError=Vec3.Dot(error,normal);bool speedValid=false,travelValid=false;double speed=0,travel=0;
            if(hasPrevious){double dt=sample.Time-previous.Time;if(dt<=0){flags|=MotionFlags.NonMonotonicTime;Reset();return Invalid(flags);}if(dt>policy.MaxGap){flags|=MotionFlags.TrackingGap;hasPrevious=false;}else{double delta=projection.ArcLengthMetres-previousProjection.ArcLengthMetres;if(delta< -policy.ReverseTolerance)flags|=MotionFlags.Reverse;if(Math.Abs(delta)>policy.MaxArcJump)flags|=MotionFlags.Discontinuity|MotionFlags.SkippedRegion;speed=delta/dt;speedValid=(flags&(MotionFlags.Discontinuity|MotionFlags.AmbiguousProjection))==0;double alpha=1-Math.Exp(-dt/policy.FilterTau);filtered=hasPrevious?filtered+alpha*(speed-filtered):speed;Vec3 motion=sample.Tip-previous.Tip;if(motion.Length>=policy.MinMotion){travelValid=true;travel=SignedAngle(projection.Tangent,motion.Normalized,normal);}}}
            if(!hasPrevious)filtered=0;bool workValid=sample.ToolForward.Normalized.Length>.999;double work=workValid?Math.Acos(Clamp(Math.Abs(Vec3.Dot(sample.ToolForward.Normalized,normal)))):0;SpeedClass classification=!speedValid?SpeedClass.Invalid:Math.Abs(filtered)<policy.MinSpeed?SpeedClass.TooSlow:Math.Abs(filtered)>policy.MaxSpeed?SpeedClass.TooFast:SpeedClass.Correct;bool valid=(flags&(MotionFlags.Discontinuity|MotionFlags.AmbiguousProjection|MotionFlags.TrackingGap))==0;previous=sample;previousProjection=projection;hasPrevious=true;return new PathMetrics(valid,projection,error,tangential,lateral,normalError,speedValid,speed,filtered,classification,travelValid,travel,workValid,work,flags);}
        static PathMetrics Invalid(MotionFlags flags)=>new(false,default,default,0,0,0,false,0,0,SpeedClass.Invalid,false,0,false,0,flags);static double Clamp(double v)=>Math.Max(-1,Math.Min(1,v));static double SignedAngle(Vec3 from,Vec3 to,Vec3 normal)=>Math.Atan2(Vec3.Dot(Vec3.Cross(from,to),normal),Clamp(Vec3.Dot(from,to)));
    }
}
