using System;

namespace WeldingTrainer.Domain
{
    public sealed class WobbleProfile
    {
        public string Id{get;}public int Version{get;}public string Hash{get;}public string SeamId{get;}public int AlgorithmVersion{get;}public double HalfAmplitudeMetres{get;}public double FrequencyHz{get;}public double InitialPhaseRadians{get;}public double SpotWidthMetres{get;}public double TargetLateralMinimumMetres{get;}public double TargetLateralMaximumMetres{get;}public double CoverageCellMetres{get;}public double MaximumIntervalSeconds{get;}
        public WobbleProfile(string id,int version,string hash,string seamId,double amplitude,double frequency,double phase,double spotWidth,double lateralMin,double lateralMax,double cell,double maximumInterval,int algorithmVersion=1)
        {if(string.IsNullOrWhiteSpace(id)||version<1||string.IsNullOrWhiteSpace(hash)||string.IsNullOrWhiteSpace(seamId)||amplitude<0||frequency<0||frequency>10000||!double.IsFinite(phase)||spotWidth<=0||lateralMax<=lateralMin||cell<=0||maximumInterval<=0||algorithmVersion!=1)throw new ArgumentException("Invalid Wobble profile");Id=id;Version=version;Hash=hash;SeamId=seamId;HalfAmplitudeMetres=amplitude;FrequencyHz=frequency;InitialPhaseRadians=phase;SpotWidthMetres=spotWidth;TargetLateralMinimumMetres=lateralMin;TargetLateralMaximumMetres=lateralMax;CoverageCellMetres=cell;MaximumIntervalSeconds=maximumInterval;AlgorithmVersion=algorithmVersion;}
    }
    public readonly struct WobbleInput
    {public readonly double TimeSeconds;public readonly PathMetrics Path;public readonly Vec3 SurfaceNormal;public readonly ActivationDecision Activation;public readonly bool QualityAcceptable;public readonly long RegistrationGeneration,RequiredRegistrationGeneration;public WobbleInput(double time,PathMetrics path,Vec3 normal,ActivationDecision activation,bool quality,long generation,long required){TimeSeconds=time;Path=path;SurfaceNormal=normal;Activation=activation;QualityAcceptable=quality;RegistrationGeneration=generation;RequiredRegistrationGeneration=required;}}
    public readonly struct WobbleDelta
    {public readonly bool Valid;public readonly string ProfileId,SeamId;public readonly ProcessMode Mode;public readonly long Epoch,RegistrationGeneration;public readonly double StartSeconds,EndSeconds,StartArcMetres,EndArcMetres,LateralMinimumMetres,LateralMaximumMetres,AreaSquareMetres;public readonly CoverageQuality Quality;public WobbleDelta(bool valid,string profile,string seam,long epoch,long generation,double startTime,double endTime,double startArc,double endArc,double lateralMin,double lateralMax,double area,CoverageQuality quality){Valid=valid;ProfileId=profile;SeamId=seam;Mode=ProcessMode.Wobble;Epoch=epoch;RegistrationGeneration=generation;StartSeconds=startTime;EndSeconds=endTime;StartArcMetres=startArc;EndArcMetres=endArc;LateralMinimumMetres=lateralMin;LateralMaximumMetres=lateralMax;AreaSquareMetres=area;Quality=quality;}}
    public sealed class FootprintCoverageSnapshot
    {public double TargetAreaSquareMetres{get;}public double AttemptedAreaSquareMetres{get;}public double AcceptableAreaSquareMetres{get;}public double PoorAreaSquareMetres=>AttemptedAreaSquareMetres-AcceptableAreaSquareMetres;public double AttemptedFraction=>TargetAreaSquareMetres<=0?0:AttemptedAreaSquareMetres/TargetAreaSquareMetres;public double AcceptableFraction=>TargetAreaSquareMetres<=0?0:AcceptableAreaSquareMetres/TargetAreaSquareMetres;public FootprintCoverageSnapshot(double target,double attempted,double acceptable){TargetAreaSquareMetres=target;AttemptedAreaSquareMetres=attempted;AcceptableAreaSquareMetres=acceptable;}}
    public sealed class WobbleResult
    {public bool OutputOn{get;}public double PhaseRadians{get;}public double ScannerOffsetMetres{get;}public Vec3 LateralAxis{get;}public double ActualCentreLateralErrorMetres{get;}public WobbleDelta Delta{get;}public FootprintCoverageSnapshot Coverage{get;}public WobbleResult(bool output,double phase,double offset,Vec3 lateral,double centreError,WobbleDelta delta,FootprintCoverageSnapshot coverage){OutputOn=output;PhaseRadians=phase;ScannerOffsetMetres=offset;LateralAxis=lateral;ActualCentreLateralErrorMetres=centreError;Delta=delta;Coverage=coverage;}}
    public sealed class WobbleProcessKernel
    {
        readonly DirectedSpline seam;readonly WobbleProfile profile;readonly byte[] cells;readonly int alongCount,lateralCount;bool active,hasPriorBasis;double epochStart,priorTime,priorArc;Vec3 priorLateral;long epoch;
        public WobbleProcessKernel(DirectedSpline seam,WobbleProfile profile,int maximumCells=1000000){this.seam=seam??throw new ArgumentNullException(nameof(seam));this.profile=profile??throw new ArgumentNullException(nameof(profile));if(seam.Id!=profile.SeamId)throw new ArgumentException("Wobble profile/seam mismatch");alongCount=Math.Max(1,(int)Math.Ceiling(seam.LengthMetres/profile.CoverageCellMetres));lateralCount=Math.Max(1,(int)Math.Ceiling((profile.TargetLateralMaximumMetres-profile.TargetLateralMinimumMetres)/profile.CoverageCellMetres));if((long)alongCount*lateralCount>maximumCells)throw new ArgumentException("Wobble coverage grid exceeds configured work bound");cells=new byte[alongCount*lateralCount];}
        public WobbleResult Update(WobbleInput i)
        {bool valid=i.Path!=null&&i.Path.Valid&&i.Path.Projection.Valid&&i.RegistrationGeneration==i.RequiredRegistrationGeneration&&i.SurfaceNormal.Finite;bool on=i.Activation.Active&&valid;Vec3 lateral=default;if(valid){lateral=Vec3.Cross(i.SurfaceNormal.Normalized,i.Path.Projection.Tangent).Normalized;if(lateral.Length<.999)on=false;else if(hasPriorBasis&&Vec3.Dot(lateral,priorLateral)<0)lateral=lateral*-1;}
            if(!on){active=false;hasPriorBasis=false;return Result(false,i.TimeSeconds,lateral,i.Path?.LateralErrorMetres??0,default);}
            if(!active){active=true;epoch++;epochStart=i.TimeSeconds;priorTime=i.TimeSeconds;priorArc=i.Path.Projection.ArcLengthMetres;priorLateral=lateral;hasPriorBasis=true;return Result(true,i.TimeSeconds,lateral,i.Path.LateralErrorMetres,default);}
            double dt=i.TimeSeconds-priorTime;if(dt<=0||dt>profile.MaximumIntervalSeconds){active=false;hasPriorBasis=false;return Result(false,i.TimeSeconds,lateral,i.Path.LateralErrorMetres,default);}
            (double minSin,double maxSin)=SinRange(RawPhase(priorTime),RawPhase(i.TimeSeconds));double radius=profile.SpotWidthMetres/2,min=Math.Max(profile.TargetLateralMinimumMetres,profile.HalfAmplitudeMetres*minSin-radius),max=Math.Min(profile.TargetLateralMaximumMetres,profile.HalfAmplitudeMetres*maxSin+radius);double a=Math.Min(priorArc,i.Path.Projection.ArcLengthMetres),b=Math.Max(priorArc,i.Path.Projection.ArcLengthMetres);double area=Mark(a,b,min,max,i.QualityAcceptable);var delta=new WobbleDelta(b>a&&max>min,profile.Id,seam.Id,epoch,i.RegistrationGeneration,priorTime,i.TimeSeconds,a,b,min,max,area,i.QualityAcceptable?CoverageQuality.Acceptable:CoverageQuality.Poor);priorTime=i.TimeSeconds;priorArc=i.Path.Projection.ArcLengthMetres;priorLateral=lateral;return Result(true,i.TimeSeconds,lateral,i.Path.LateralErrorMetres,delta);}
        public WobbleResult Stop(double time){active=false;hasPriorBasis=false;return Result(false,time,default,0,default);}
        public double Phase(double time)=>Normalize(RawPhase(time));double RawPhase(double time)=>profile.InitialPhaseRadians+2*Math.PI*profile.FrequencyHz*(time-epochStart);
        WobbleResult Result(bool output,double time,Vec3 lateral,double centreError,WobbleDelta delta){double phase=active?Phase(time):profile.InitialPhaseRadians;return new WobbleResult(output,phase,profile.HalfAmplitudeMetres*Math.Sin(phase),lateral,centreError,delta,Snapshot());}
        double Mark(double start,double end,double min,double max,bool acceptable){if(end<=start||max<=min)return 0;int a0=Math.Max(0,(int)Math.Floor(start/profile.CoverageCellMetres)),a1=Math.Min(alongCount-1,(int)Math.Floor((end-1e-12)/profile.CoverageCellMetres));int l0=Math.Max(0,(int)Math.Floor((min-profile.TargetLateralMinimumMetres)/profile.CoverageCellMetres)),l1=Math.Min(lateralCount-1,(int)Math.Floor((max-profile.TargetLateralMinimumMetres-1e-12)/profile.CoverageCellMetres));double newly=0;for(int a=a0;a<=a1;a++)for(int l=l0;l<=l1;l++){int index=a*lateralCount+l;byte before=cells[index];if(before==0)newly+=profile.CoverageCellMetres*profile.CoverageCellMetres;if(before==0)cells[index]=(byte)(acceptable?1:2);else if(!acceptable)cells[index]=2;}return newly;}
        FootprintCoverageSnapshot Snapshot(){int attempted=0,acceptable=0;foreach(byte c in cells){if(c!=0)attempted++;if(c==1)acceptable++;}double cellArea=profile.CoverageCellMetres*profile.CoverageCellMetres,target=seam.LengthMetres*(profile.TargetLateralMaximumMetres-profile.TargetLateralMinimumMetres);return new FootprintCoverageSnapshot(target,Math.Min(target,attempted*cellArea),Math.Min(target,acceptable*cellArea));}
        static (double,double) SinRange(double start,double end){double span=end-start;if(span<0)throw new ArgumentException("Wobble phase reversed");if(span>=2*Math.PI-1e-12)return(-1,1);double min=Math.Min(Math.Sin(start),Math.Sin(end)),max=Math.Max(Math.Sin(start),Math.Sin(end));double first=Math.Ceiling((start-Math.PI/2)/Math.PI);double last=Math.Floor((end-Math.PI/2)/Math.PI);for(double k=first;k<=last;k++){double value=Math.Sin(Math.PI/2+k*Math.PI);min=Math.Min(min,value);max=Math.Max(max,value);}return(min,max);}
        static double Normalize(double value){double two=2*Math.PI;value%=two;return value<0?value+two:value;}
    }
}
