using System;
using System.Collections.Generic;
using System.Linq;
using WeldingTrainer.Domain;

namespace WeldingTrainer.Application
{
    public enum TrainingCommandType { EmergencyStop, Abort, FinishSession, FinishAttempt, Pause, ResetEmergencyStop, Disarm, DisconnectClamp, ConnectClamp, SelectWeldingNozzle, SelectCleaningNozzle, Arm, Resume }
    public readonly struct TrainingCommand { public readonly TrainingCommandType Type; public readonly double Time; public readonly long Sequence; public TrainingCommand(TrainingCommandType type,double time,long sequence){Type=type;Time=time;Sequence=sequence;} public int Priority=>Type switch{TrainingCommandType.EmergencyStop=>0,TrainingCommandType.Abort=>1,TrainingCommandType.FinishSession=>2,TrainingCommandType.FinishAttempt=>3,TrainingCommandType.Pause=>4,TrainingCommandType.ResetEmergencyStop=>5,TrainingCommandType.Disarm=>6,TrainingCommandType.DisconnectClamp=>7,TrainingCommandType.ConnectClamp=>8,TrainingCommandType.SelectWeldingNozzle=>9,TrainingCommandType.SelectCleaningNozzle=>9,TrainingCommandType.Arm=>10,TrainingCommandType.Resume=>11,_=>99}; }

    public sealed class TrainingCoordinator : IDisposable
    {
        readonly IMonotonicClock _clock; readonly IIdSource _ids; readonly ITrainingInputPort _input; readonly IRegistrationPort _registration; readonly ISafetyPort _safety; readonly IRecorderPort _recorder; readonly ISnapshotSink _sink; readonly IHapticStop _haptics;
        readonly List<TrainingCommand> _commands=new(); long _commandSeq,_eventSeq,_snapshotSeq; string _sessionId; AttemptConfiguration _attempt; SessionState _state=SessionState.Idle; ActivationState _activation=ActivationState.Inhibited; NozzleState _nozzle=NozzleState.Unknown; ClampState _clamp=ClampState.Disconnected; BlockReason _reasons=BlockReason.NoSession; long _registrationGeneration; bool _estop,_releaseRequired,_disposed;
        public ProcessSnapshot Current{get;private set;} public event Action<ProcessEvent> EventEmitted;
        public TrainingCoordinator(IMonotonicClock clock,IIdSource ids,ITrainingInputPort input,IRegistrationPort registration,ISafetyPort safety,IRecorderPort recorder,ISnapshotSink sink,IHapticStop haptics){_clock=clock??throw new ArgumentNullException(nameof(clock));_ids=ids??throw new ArgumentNullException(nameof(ids));_input=input??throw new ArgumentNullException(nameof(input));_registration=registration??throw new ArgumentNullException(nameof(registration));_safety=safety??throw new ArgumentNullException(nameof(safety));_recorder=recorder??throw new ArgumentNullException(nameof(recorder));_sink=sink??throw new ArgumentNullException(nameof(sink));_haptics=haptics??throw new ArgumentNullException(nameof(haptics));Publish(default);}
        public void StartSession(){if(_state!=SessionState.Idle&&_state!=SessionState.Completed&&_state!=SessionState.Aborted)throw new InvalidOperationException("Session active");_sessionId=_ids.NewId();_attempt=null;_nozzle=NozzleState.Unknown;_clamp=ClampState.Disconnected;_estop=false;_releaseRequired=true;Transition(SessionState.Initializing,ProcessEventType.SessionStarted,"created");Transition(SessionState.Registering,ProcessEventType.StateChanged,"await-registration");}
        public AttemptConfiguration PrepareAttempt(ProcessConfiguration process){if(_state!=SessionState.Selecting&&_state!=SessionState.Reviewing)throw new InvalidOperationException("Prepare only from Selecting/Reviewing");if(_activation==ActivationState.Armed||_activation==ActivationState.Active)throw new InvalidOperationException("Disarm first");var registration=_registration.Capture(_clock.Seconds);if(!registration.Valid||registration.FixtureId!=process.FixtureId)throw new InvalidOperationException("Registration/config mismatch");_attempt=new AttemptConfiguration(_ids.NewId(),process,registration.RegistrationGeneration);_recorder.Begin(_attempt);_activation=ActivationState.ReadyDisarmed;Transition(SessionState.Ready,ProcessEventType.AttemptPrepared,process.Profile.Hash);return _attempt;}
        public long Submit(TrainingCommandType type,double time){long s=++_commandSeq;_commands.Add(new TrainingCommand(type,time,s));return s;}
        public void Tick(){double now=_clock.Seconds;TrainingInput input=_input.Capture(now);RegistrationInput registration=_registration.Capture(now);if(input.EmergencyStopPressed)_commands.Add(new TrainingCommand(TrainingCommandType.EmergencyStop,now,++_commandSeq));foreach(var c in _commands.Where(x=>x.Time<=now).OrderBy(x=>x.Time).ThenBy(x=>x.Priority).ThenBy(x=>x.Sequence).ToArray()){Apply(c,input);_commands.Remove(c);}if(_state==SessionState.Registering&&registration.Valid){_registrationGeneration=registration.RegistrationGeneration;Emit(ProcessEventType.RegistrationAccepted,registration.FixtureId,now);Transition(SessionState.Selecting,ProcessEventType.StateChanged,"select");}if(_state==SessionState.Ready||_state==SessionState.Running||_state==SessionState.Suspended)Evaluate(input,registration,now);Publish(input);}
        void Evaluate(TrainingInput input,RegistrationInput registration,double now){BlockReason r=BlockReason.None;if(!registration.Available||!registration.Valid)r|=BlockReason.RegistrationInvalid;if(registration.OriginGeneration!=input.OriginGeneration)r|=BlockReason.OriginMismatch;if(!input.HeadValid)r|=BlockReason.HeadInvalid;if(!input.ToolValid)r|=BlockReason.ToolInvalid;if(_attempt!=null&&now-input.CapturedSeconds>_attempt.Process.Profile.MaximumSampleGapSeconds)r|=BlockReason.StaleInput;if(_nozzle==NozzleState.Unknown)r|=BlockReason.NozzleUnknown;else if(_attempt!=null&&((_attempt.Process.Profile.Mode<=ProcessMode.Pulsed&&_nozzle!=NozzleState.Welding)||(_attempt.Process.Profile.Mode>=ProcessMode.PreWeldCleaning&&_nozzle!=NozzleState.Cleaning)))r|=BlockReason.NozzleMismatch;if(_clamp!=ClampState.Connected)r|=BlockReason.ClampDisconnected;if(!_recorder.Available)r|=BlockReason.RecorderUnavailable;if(_estop)r|=BlockReason.EmergencyStop;if(_releaseRequired)r|=BlockReason.TriggerReleaseRequired;SafetyInput safety=_attempt==null?default:_safety.Evaluate(input,registration,_attempt);if(!safety.Available)r|=BlockReason.SafetyUnknown;else if(!safety.Allowed)r|=BlockReason.SafetyRejected|safety.Reasons;if(safety.FaultLatched)r|=BlockReason.FaultLatched;if(_releaseRequired&&input.TriggerReleased&&!input.TriggerPressed)_releaseRequired=false;if(_state==SessionState.Running&&r!=BlockReason.None){_activation=_estop?ActivationState.ResetRequired:ActivationState.Inhibited;_releaseRequired=true;_haptics.StopImmediately();Transition(SessionState.Suspended,ProcessEventType.Suspended,r.ToString());}else if(_state==SessionState.Running){_activation=input.TriggerPressed?ActivationState.Active:ActivationState.Armed;}_reasons=r;}
        void Apply(TrainingCommand c,TrainingInput input){switch(c.Type){case TrainingCommandType.EmergencyStop:if(_estop)break;_estop=true;_releaseRequired=true;_activation=ActivationState.ResetRequired;_haptics.StopImmediately();Emit(ProcessEventType.EmergencyStop,"latched",c.Time);if(_state==SessionState.Running)Transition(SessionState.Suspended,ProcessEventType.Suspended,"estop");break;case TrainingCommandType.ResetEmergencyStop:if(_estop&&!input.TriggerPressed){_estop=false;_activation=ActivationState.ReadyDisarmed;Emit(ProcessEventType.EmergencyReset,"reset",c.Time);}break;case TrainingCommandType.Abort:Finish(true);_state=SessionState.Aborted;Emit(ProcessEventType.SessionAborted,"abort",c.Time);break;case TrainingCommandType.FinishAttempt:Finish(false);break;case TrainingCommandType.FinishSession:if(_state!=SessionState.Reviewing)throw new InvalidOperationException();_state=SessionState.Completed;Emit(ProcessEventType.SessionCompleted,"complete",c.Time);break;case TrainingCommandType.Pause:if(_state==SessionState.Running){_activation=ActivationState.ReadyDisarmed;Transition(SessionState.Suspended,ProcessEventType.Suspended,"pause");}break;case TrainingCommandType.Resume:if(_state!=SessionState.Suspended)throw new InvalidOperationException();_activation=ActivationState.ReadyDisarmed;Transition(SessionState.Ready,ProcessEventType.Resumed,"ready");break;case TrainingCommandType.Disarm:_activation=ActivationState.ReadyDisarmed;_releaseRequired=input.TriggerPressed;Emit(ProcessEventType.Disarmed,"disarm",c.Time);break;case TrainingCommandType.ConnectClamp:Mutable();_clamp=ClampState.Connected;Emit(ProcessEventType.ClampChanged,"connected",c.Time);break;case TrainingCommandType.DisconnectClamp:_clamp=ClampState.Disconnected;if(_state==SessionState.Running){_activation=ActivationState.Inhibited;Transition(SessionState.Suspended,ProcessEventType.Suspended,"clamp");}Emit(ProcessEventType.ClampChanged,"disconnected",c.Time);break;case TrainingCommandType.SelectWeldingNozzle:Mutable();_nozzle=NozzleState.Welding;Emit(ProcessEventType.NozzleChanged,"welding",c.Time);break;case TrainingCommandType.SelectCleaningNozzle:Mutable();_nozzle=NozzleState.Cleaning;Emit(ProcessEventType.NozzleChanged,"cleaning",c.Time);break;case TrainingCommandType.Arm:if(_state!=SessionState.Ready)throw new InvalidOperationException();if(input.TriggerPressed||_releaseRequired){_releaseRequired=true;break;}_activation=ActivationState.Armed;Transition(SessionState.Running,ProcessEventType.Armed,"armed");break;}}
        void Mutable(){if(_state==SessionState.Running||_activation==ActivationState.Armed||_activation==ActivationState.Active)throw new InvalidOperationException("Preparation locked");}
        void Finish(bool interrupted){if(_attempt==null)return;_activation=ActivationState.Inhibited;Transition(SessionState.Saving,ProcessEventType.SavingStarted,interrupted?"interrupted":"complete");if(!_recorder.Finish(_attempt.AttemptId,interrupted,out string error))Transition(SessionState.Faulted,ProcessEventType.SaveFailed,error);else Transition(SessionState.Reviewing,ProcessEventType.ReviewReady,_attempt.AttemptId);}
        void Transition(SessionState state,ProcessEventType type,string payload){_state=state;Emit(type,payload,_clock.Seconds);}void Emit(ProcessEventType type,string payload,double time){var e=new ProcessEvent(++_eventSeq,time,_sessionId,_attempt?.AttemptId,0,_registrationGeneration,_attempt?.Process.Profile.Hash,type,payload);EventEmitted?.Invoke(e);if(_recorder.Available)_recorder.Append(e);}void Publish(TrainingInput input){Current=new ProcessSnapshot(++_snapshotSeq,_sessionId,_attempt?.AttemptId,_state,_activation,_nozzle,_clamp,_reasons,input.TriggerPressed);_sink.Publish(Current);}public void Dispose(){if(_disposed)return;_disposed=true;_activation=ActivationState.Inhibited;_haptics.StopImmediately();_registration.Teardown();_recorder.Teardown();}
    }
}
