using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using WeldingTrainer.Application;
using WeldingTrainer.Domain;

namespace WeldingTrainer.Infrastructure.Local
{
    public sealed class RecordingOptions
    {
        public int QueueCapacity{get;} public int CriticalReserve{get;} public long ChunkBytes{get;} public double ChunkSeconds{get;} public int MaximumSessions{get;}
        public RecordingOptions(int queueCapacity=4096,int criticalReserve=64,long chunkBytes=2*1024*1024,double chunkSeconds=300,int maximumSessions=20)
        {if(queueCapacity<16||criticalReserve<1||criticalReserve>=queueCapacity||chunkBytes<1024||chunkSeconds<=0||maximumSessions<1)throw new ArgumentException("Invalid recording options");QueueCapacity=queueCapacity;CriticalReserve=criticalReserve;ChunkBytes=chunkBytes;ChunkSeconds=chunkSeconds;MaximumSessions=maximumSessions;}
    }
    public sealed class SessionMetadata
    {
        public string SessionId{get;} public string AppVersion{get;} public string EvaluatorVersion{get;} public string BindingId{get;} public string BindingHash{get;} public string RegistrationEvidence{get;}
        public SessionMetadata(string sessionId,string appVersion,string evaluatorVersion,string bindingId,string bindingHash,string registrationEvidence)
        {SessionId=Required(sessionId);AppVersion=Required(appVersion);EvaluatorVersion=Required(evaluatorVersion);BindingId=Required(bindingId);BindingHash=Required(bindingHash);RegistrationEvidence=registrationEvidence??"";}
        static string Required(string value)=>string.IsNullOrWhiteSpace(value)?throw new ArgumentException("Metadata field required"):value;
    }
    public readonly struct SessionInspection {public readonly bool Complete,HasPartialFiles,ManifestPresent;public SessionInspection(bool complete,bool partial,bool manifest){Complete=complete;HasPartialFiles=partial;ManifestPresent=manifest;}}
    public sealed class LocalSessionRecorder : IRecorderPort,IAttemptDataRecorder
    {
        readonly string sessionsRoot,sessionRoot; readonly SessionMetadata metadata; readonly RecordingOptions options; readonly Action<string> writeGuard; readonly BlockingCollection<Item> queue; readonly Thread worker; readonly object gate=new();
        readonly List<ChunkInfo> chunks=new(); AttemptConfiguration attempt; AttemptMetricsAccumulator metrics; StreamWriter writer; string partialPath; int chunkIndex,flushRequested,flushCompleted; long chunkStartBytes,dropped; double chunkStartSeconds; volatile bool failed,disposed; string failure;
        public bool Available=>!failed&&!disposed; public long DroppedSamples=>Interlocked.Read(ref dropped);
        public LocalSessionRecorder(string persistentDataRoot,SessionMetadata metadata,RecordingOptions options=null,Action<string> writeGuard=null)
        {if(string.IsNullOrWhiteSpace(persistentDataRoot))throw new ArgumentException("Injected persistent data root required");this.metadata=metadata??throw new ArgumentNullException(nameof(metadata));this.options=options??new RecordingOptions();this.writeGuard=writeGuard;sessionsRoot=Path.Combine(Path.GetFullPath(persistentDataRoot),"Sessions");sessionRoot=Path.Combine(sessionsRoot,Safe(metadata.SessionId));Directory.CreateDirectory(sessionRoot);WriteAtomic(Path.Combine(sessionRoot,"session.json"),SessionJson(false));queue=new BlockingCollection<Item>(this.options.QueueCapacity);worker=new Thread(Work){IsBackground=true,Name="Training session writer"};worker.Start();ApplyRetention();}
        public void Begin(AttemptConfiguration value)
        {if(value==null)throw new ArgumentNullException(nameof(value));lock(gate){EnsureAvailable();if(attempt!=null)throw new InvalidOperationException("Attempt already active");attempt=value;metrics=new AttemptMetricsAccumulator();chunks.Clear();chunkIndex=0;OpenChunk(0);WriteAtomic(Path.Combine(AttemptRoot,"attempt.json"),AttemptJson(value));}}
        public bool TryAppend(AttemptSample sample)
        {if(!Available||attempt==null)return false;if(queue.Count>=options.QueueCapacity-options.CriticalReserve||!queue.TryAdd(Item.Sample(sample))){Interlocked.Increment(ref dropped);return false;}return true;}
        public void Append(ProcessEvent value)
        {if(!Available)return;try{queue.Add(Item.Event(value));}catch(Exception e){Fail(e);}}
        public bool Finish(string attemptId,bool interrupted,out string error)
        {lock(gate){if(attempt==null||attempt.AttemptId!=attemptId){error="Attempt mismatch";return false;}int target=++flushRequested;if(!failed)queue.Add(Item.Flush(target));while(flushCompleted<target&&!failed)Monitor.Wait(gate,50);CloseChunk();if(failed){attempt=null;metrics=null;error=failure;return false;}AttemptSummary summary=metrics.Finish(!interrupted,interrupted);bool complete=DroppedSamples==0;WriteAtomic(Path.Combine(AttemptRoot,"summary.json"),SummaryJson(summary,interrupted,complete));WriteAtomic(Path.Combine(AttemptRoot,"manifest.json"),ManifestJson(complete));attempt=null;metrics=null;error=failure;return complete;}}
        public void Teardown(){Dispose();}
        public void Dispose(){if(disposed)return;disposed=true;queue.CompleteAdding();worker.Join(3000);lock(gate){bool complete=!failed&&attempt==null;CloseChunk();WriteAtomic(Path.Combine(sessionRoot,"session.json"),SessionJson(complete));}}
        public static SessionInspection Inspect(string sessionDirectory)
        {if(string.IsNullOrWhiteSpace(sessionDirectory)||!Directory.Exists(sessionDirectory))return default;bool partial=Directory.EnumerateFiles(sessionDirectory,"*.partial",SearchOption.AllDirectories).Any();string[] attempts=Directory.Exists(Path.Combine(sessionDirectory,"attempts"))?Directory.GetDirectories(Path.Combine(sessionDirectory,"attempts")):Array.Empty<string>();bool manifests=attempts.Length>0&&attempts.All(x=>File.Exists(Path.Combine(x,"manifest.json")));bool sessionComplete=File.Exists(Path.Combine(sessionDirectory,"session.json"))&&File.ReadAllText(Path.Combine(sessionDirectory,"session.json")).Contains("\"completed\":true");return new SessionInspection(sessionComplete&&manifests&&!partial,partial,manifests);}
        void Work(){try{foreach(Item item in queue.GetConsumingEnumerable()){lock(gate){if(item.Kind==ItemKind.Sample&&attempt!=null){Rotate(item.SampleValue.TimeSeconds);writeGuard?.Invoke(partialPath);writer.WriteLine(SampleJson(item.SampleValue));metrics.Add(item.SampleValue);}else if(item.Kind==ItemKind.Event&&attempt!=null){writeGuard?.Invoke(partialPath);writer.WriteLine(EventJson(item.EventValue));}writer?.Flush();if(item.Kind==ItemKind.Flush)flushCompleted=item.FlushId;Monitor.PulseAll(gate);}}}catch(Exception e){Fail(e);lock(gate)Monitor.PulseAll(gate);}}
        void Rotate(double now){if(writer==null){OpenChunk(now);return;}if(writer.BaseStream.Position-chunkStartBytes>=options.ChunkBytes||now-chunkStartSeconds>=options.ChunkSeconds){CloseChunk();OpenChunk(now);}}
        void OpenChunk(double start){string root=AttemptRoot;Directory.CreateDirectory(root);partialPath=Path.Combine(root,$"records-{chunkIndex:D4}.jsonl.partial");writer=new StreamWriter(new FileStream(partialPath,FileMode.Create,FileAccess.Write,FileShare.Read),new UTF8Encoding(false));chunkStartBytes=0;chunkStartSeconds=start;}
        void CloseChunk(){if(writer==null)return;writer.Flush();writer.Dispose();string final=partialPath.Substring(0,partialPath.Length-8);File.Move(partialPath,final);byte[] bytes=File.ReadAllBytes(final);chunks.Add(new ChunkInfo(Path.GetFileName(final),bytes.LongLength,Hash(bytes)));writer=null;partialPath=null;chunkIndex++;}
        string AttemptRoot=>Path.Combine(sessionRoot,"attempts",Safe(attempt.AttemptId));
        void ApplyRetention(){Directory.CreateDirectory(sessionsRoot);foreach(DirectoryInfo dir in new DirectoryInfo(sessionsRoot).GetDirectories().Where(x=>!string.Equals(x.FullName,sessionRoot,StringComparison.OrdinalIgnoreCase)).OrderByDescending(x=>x.LastWriteTimeUtc).Skip(options.MaximumSessions-1)){try{dir.Delete(true);}catch{}}}
        void EnsureAvailable(){if(!Available)throw new IOException(failure??"Recorder unavailable");}
        void Fail(Exception e){failed=true;failure=e.GetType().Name+": "+e.Message;}
        void WriteAtomic(string path,string content){writeGuard?.Invoke(path);Directory.CreateDirectory(Path.GetDirectoryName(path));string partial=path+".partial";File.WriteAllText(partial,content,new UTF8Encoding(false));if(File.Exists(path))File.Delete(path);File.Move(partial,path);}
        string SessionJson(bool completed)=>$"{{\"schemaVersion\":1,\"sessionId\":{Q(metadata.SessionId)},\"appVersion\":{Q(metadata.AppVersion)},\"evaluatorVersion\":{Q(metadata.EvaluatorVersion)},\"bindingId\":{Q(metadata.BindingId)},\"bindingHash\":{Q(metadata.BindingHash)},\"registrationEvidence\":{Q(metadata.RegistrationEvidence)},\"completed\":{B(completed)}}}";
        string AttemptJson(AttemptConfiguration a)=>$"{{\"schemaVersion\":1,\"attemptId\":{Q(a.AttemptId)},\"workpieceId\":{Q(a.Process.FixtureId)},\"seamId\":{Q(a.Process.SeamId)},\"profileId\":{Q(a.Process.Profile.Id)},\"profileVersion\":{a.Process.Profile.Version},\"profileHash\":{Q(a.Process.Profile.Hash)},\"mode\":{Q(a.Process.Profile.Mode.ToString())},\"registrationGeneration\":{a.RegistrationGeneration}}}";
        string SummaryJson(AttemptSummary s,bool interrupted,bool complete)=>$"{{\"schemaVersion\":1,\"complete\":{B(complete)},\"interrupted\":{B(interrupted)},\"droppedSamples\":{DroppedSamples},\"durationSeconds\":{N(s.DurationSeconds)},\"validSeconds\":{N(s.ValidSeconds)},\"invalidSeconds\":{N(s.InvalidSeconds)},\"blockedTriggerSeconds\":{N(s.BlockedTriggerSeconds)},\"meanPositionErrorMetres\":{N(s.MeanPositionErrorMetres)},\"maximumPositionErrorMetres\":{N(s.MaximumPositionErrorMetres)},\"positionInRangeFraction\":{N(s.PositionInRangeFraction)},\"speedInRangeFraction\":{N(s.SpeedInRangeFraction)},\"meanTravelAngleErrorRadians\":{N(s.MeanTravelAngleErrorRadians)},\"meanWorkAngleErrorRadians\":{N(s.MeanWorkAngleErrorRadians)},\"coverageFraction\":{N(s.CoverageFraction)},\"missedFraction\":{N(s.MissedFraction)},\"coveredLengthMetres\":{N(s.CoveredLengthMetres)},\"missedLengthMetres\":{N(s.MissedLengthMetres)},\"cleaningCoverageFraction\":{N(s.CleaningCoverageFraction)},\"coveredAreaSquareMetres\":{N(s.CoveredAreaSquareMetres)},\"missedAreaSquareMetres\":{N(s.MissedAreaSquareMetres)},\"reverseCount\":{s.ReverseCount},\"maximumProgress\":{N(s.MaximumProgress)},\"scored\":{B(s.Scored&&complete)}}}";
        string ManifestJson(bool complete)=>$"{{\"schemaVersion\":1,\"complete\":{B(complete)},\"chunks\":[{string.Join(",",chunks.Select(x=>$"{{\"file\":{Q(x.File)},\"bytes\":{x.Bytes},\"sha256\":{Q(x.Sha256)}}}"))}]}}";
        static string SampleJson(AttemptSample s)=>$"{{\"kind\":\"sample\",\"schemaVersion\":1,\"timeSeconds\":{N(s.TimeSeconds)},\"deltaSeconds\":{N(s.DeltaSeconds)},\"poseValid\":{B(s.PoseValid)},\"registrationValid\":{B(s.RegistrationValid)},\"inputGeneration\":{s.InputGeneration},\"registrationGeneration\":{s.RegistrationGeneration},\"tip\":[{N(s.TipPositionMetres.X)},{N(s.TipPositionMetres.Y)},{N(s.TipPositionMetres.Z)}],\"rotation\":[{N(s.TipRotation.X)},{N(s.TipRotation.Y)},{N(s.TipRotation.Z)},{N(s.TipRotation.W)}],\"progress\":{N(s.Progress)},\"positionErrorMetres\":{N(s.PositionErrorMetres)},\"speedMps\":{N(s.SpeedMps)},\"speedClass\":{Q(s.SpeedClass.ToString())},\"travelAngleErrorRadians\":{N(s.TravelAngleErrorRadians)},\"workAngleErrorRadians\":{N(s.WorkAngleErrorRadians)},\"assistance\":{N(s.Assistance)},\"trigger\":{B(s.TriggerPressed)},\"permission\":{B(s.Permission)},\"active\":{B(s.Active)},\"withinTolerance\":{B(s.WithinPositionTolerance)},\"reverse\":{B(s.ReverseMotion)},\"covered\":{B(s.Covered)},\"newlyCoveredLengthMetres\":{N(s.NewlyCoveredLengthMetres)},\"targetLengthMetres\":{N(s.TargetLengthMetres)},\"newlyCoveredAreaSquareMetres\":{N(s.NewlyCoveredAreaSquareMetres)},\"targetAreaSquareMetres\":{N(s.TargetAreaSquareMetres)},\"blockReasons\":{Q(s.BlockReasons.ToString())}}}";
        static string EventJson(ProcessEvent e)=>$"{{\"kind\":\"event\",\"schemaVersion\":1,\"sequence\":{e.Sequence},\"timeSeconds\":{N(e.MonotonicSeconds)},\"type\":{Q(e.Type.ToString())},\"payload\":{Q(e.Payload)}}}";
        static string Q(string s)=>"\""+(s??"").Replace("\\","\\\\").Replace("\"","\\\"").Replace("\r","\\r").Replace("\n","\\n")+"\"";static string N(double n)=>double.IsFinite(n)?n.ToString("R",CultureInfo.InvariantCulture):"null";static string B(bool b)=>b?"true":"false";static string Safe(string s)=>string.Concat(s.Select(c=>char.IsLetterOrDigit(c)||c=='-'||c=='_'?c:'_'));static string Hash(byte[] b){using var h=SHA256.Create();return BitConverter.ToString(h.ComputeHash(b)).Replace("-","").ToLowerInvariant();}
        enum ItemKind { Sample,Event,Flush } readonly struct Item {public readonly ItemKind Kind;public readonly AttemptSample SampleValue;public readonly ProcessEvent EventValue;public readonly int FlushId;Item(ItemKind kind,AttemptSample sample,ProcessEvent e,int flushId){Kind=kind;SampleValue=sample;EventValue=e;FlushId=flushId;}public static Item Sample(AttemptSample s)=>new(ItemKind.Sample,s,null,0);public static Item Event(ProcessEvent e)=>new(ItemKind.Event,default,e,0);public static Item Flush(int id)=>new(ItemKind.Flush,default,null,id);}
        readonly struct ChunkInfo {public readonly string File,Sha256;public readonly long Bytes;public ChunkInfo(string file,long bytes,string sha){File=file;Bytes=bytes;Sha256=sha;}}
    }
}
